import fs from "node:fs";
import path from "node:path";
import { ComparisonDataSchema } from "../llm/comparison";
import { normalizeComparison, normalizeGeneratedText } from "../llm/output-normalizer";
import type { ComparisonData } from "../llm/types";
import { BRAND_ASSETS, BRAND_LOCKUP } from "../brand/lockup";
import { isRedundantArtifactTitle, normalizeArtifactTitle } from "../llm/title";
import { buildEmailSubject } from "./subject";

/**
 * Delivery-only email renderer. It normalizes and escapes generated content a
 * final time, then produces controlled email-safe HTML, plain text, and inline
 * brand attachments from one input object.
 */
const DISCLAIMER =
  "This content is generated by EquityIQ for informational purposes only. It does not constitute legal, tax, or financial advice. Consult qualified professionals before making decisions based on this information.";

const FONT_STACK = "'Inter',Arial,sans-serif";

export type EmailInlineAttachment = {
  filename: string;
  content: Buffer;
  contentType: string;
  contentId: string;
};

export type ArtifactEmailInput = {
  title: string;
  question?: string;
  bodyMarkdown: string;
  comparison?: ComparisonData;
  appUrl: string;
  recipient?: string;
  authenticatedUser?: {
    email?: string;
    name?: string;
  };
};

export type ArtifactEmail = {
  subject: string;
  html: string;
  text: string;
  inlineAttachments: EmailInlineAttachment[];
};

type EmailTable = {
  headers: string[];
  rows: string[][];
};

type EmailBlock =
  | { kind: "heading"; text: string }
  | { kind: "paragraph"; text: string }
  | { kind: "list"; ordered: boolean; items: string[] }
  | { kind: "callout"; text: string }
  | { kind: "table"; table: EmailTable };

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => {
    const entities: Record<string, string> = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#039;",
    };
    return entities[character];
  });
}

function safeHref(value: string): string | null {
  // Generated content may link to an internal article, but it must not be
  // able to introduce arbitrary external destinations into a delivered email.
  return (value.startsWith("/") && !value.startsWith("//")) || value.startsWith("#") ? value : null;
}

function renderInlineHtml(value: string): string {
  const input = value.trim();
  const tokenPattern = /\*\*[^*]+\*\*|__[^_]+__|`[^`]+`|\[[^\]]+\]\([^\s)]+\)|(?<!\*)\*[^*]+\*(?!\*)/g;
  const parts: string[] = [];
  let cursor = 0;

  for (const match of input.matchAll(tokenPattern)) {
    const token = match[0];
    const index = match.index ?? 0;
    if (index > cursor) parts.push(escapeHtml(input.slice(cursor, index)));

    if ((token.startsWith("**") && token.endsWith("**")) || (token.startsWith("__") && token.endsWith("__"))) {
      parts.push(`<strong style="color:#111827;font-weight:600;">${escapeHtml(token.slice(2, -2))}</strong>`);
    } else if (token.startsWith("`") && token.endsWith("`")) {
      parts.push(`<code style="font-family:monospace;">${escapeHtml(token.slice(1, -1))}</code>`);
    } else if (token.startsWith("[") && token.includes("](")) {
      const link = token.match(/^\[([^\]]+)\]\(([^\s)]+)\)$/);
      const href = link ? safeHref(link[2]) : null;
      parts.push(href
        ? `<a href="${escapeHtml(href)}" target="_blank" style="color:#7C3AED;text-decoration:none;">${escapeHtml(link?.[1] ?? "")}</a>`
        : escapeHtml(link?.[1] ?? token));
    } else {
      parts.push(`<em>${escapeHtml(token.slice(1, -1))}</em>`);
    }
    cursor = index + token.length;
  }

  if (cursor < input.length) parts.push(escapeHtml(input.slice(cursor)));
  return parts.join("");
}

function cleanPlainText(value: string): string {
  return value
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
}

function cleanHeading(value: string): string {
  return cleanPlainText(value).replace(/[\s:.]+$/, "").trim();
}

function isTableSeparator(line: string): boolean {
  return /^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$/.test(line);
}

function splitTableRow(line: string): string[] {
  const value = line.trim().replace(/^\|/, "").replace(/\|$/, "");
  return value.split("|").map((cell) => normalizeGeneratedText(cell).trim());
}

function stripEmailFraming(bodyMarkdown: string): string {
  const lines = normalizeGeneratedText(bodyMarkdown).split(/\r?\n/);
  while (lines[0] !== undefined && !lines[0].trim()) lines.shift();
  while (lines[0] && /^\s*(?:subject(?:\s+line)?|re)\s*:/i.test(lines[0])) lines.shift();
  while (lines[0] && /^\s*(?:hi|hello|dear)\b[^\n]*[,!:]?\s*$/i.test(lines[0])) lines.shift();

  while (lines.length && !lines[lines.length - 1].trim()) lines.pop();
  if (lines.length && /^(?:best|best regards|kind regards|regards|sincerely|thank you)[,!]?$/i.test(lines[lines.length - 1].trim())) {
    lines.pop();
    while (lines.length && !lines[lines.length - 1].trim()) lines.pop();
    if (lines.length && !lines[lines.length - 1].trim().startsWith("## ")) lines.pop();
  }
  return lines.join("\n").trim();
}

function parseEmailBlocks(bodyMarkdown: string): EmailBlock[] {
  const lines = stripEmailFraming(bodyMarkdown).split(/\r?\n/);
  const blocks: EmailBlock[] = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index].trim();
    if (!line) {
      index += 1;
      continue;
    }

    const heading = line.match(/^#{1,6}\s+(.+)$/);
    if (heading) {
      blocks.push({ kind: "heading", text: cleanHeading(heading[1]) });
      index += 1;
      continue;
    }

    if (line.startsWith("> ")) {
      const callout: string[] = [];
      while (index < lines.length && lines[index].trim().startsWith("> ")) {
        callout.push(lines[index].trim().replace(/^>\s*/, ""));
        index += 1;
      }
      blocks.push({ kind: "callout", text: callout.join(" ").trim() });
      continue;
    }

    if (line.includes("|") && index + 1 < lines.length && isTableSeparator(lines[index + 1])) {
      const headers = splitTableRow(line);
      index += 2;
      const rows: string[][] = [];
      while (index < lines.length && lines[index].trim().includes("|")) {
        rows.push(splitTableRow(lines[index]));
        index += 1;
      }
      if (headers.length > 1 && rows.length > 0) blocks.push({ kind: "table", table: { headers, rows } });
      continue;
    }

    if (/^[-*]\s+/.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^\s*[-*]\s+/.test(lines[index])) {
        items.push(lines[index].replace(/^\s*[-*]\s+/, "").trim());
        index += 1;
      }
      blocks.push({ kind: "list", ordered: false, items });
      continue;
    }

    if (/^\d+\.\s+/.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^\s*\d+\.\s+/.test(lines[index])) {
        items.push(lines[index].replace(/^\s*\d+\.\s+/, "").trim());
        index += 1;
      }
      blocks.push({ kind: "list", ordered: true, items });
      continue;
    }

    const paragraph: string[] = [line];
    index += 1;
    while (index < lines.length) {
      const next = lines[index].trim();
      if (!next || /^#{1,6}\s+/.test(next) || /^[-*]\s+/.test(next) || /^\d+\.\s+/.test(next) || next.startsWith("> ")) break;
      if (next.includes("|") && index + 1 < lines.length && isTableSeparator(lines[index + 1])) break;
      paragraph.push(next);
      index += 1;
    }
    blocks.push({ kind: "paragraph", text: paragraph.join(" ").trim() });
  }

  return blocks.filter((block) => block.kind !== "paragraph" || block.text.length > 0);
}

function renderList(block: Extract<EmailBlock, { kind: "list" }>): string {
  const items = block.items.map((item, index) => `
    <tr>
      <td style="width:20px;vertical-align:top;color:#7C3AED;font-size:13px;line-height:1.65;">${block.ordered ? `${index + 1}.` : "•"}</td>
      <td style="font-family:${FONT_STACK};font-size:13px;color:#374151;line-height:1.65;padding-bottom:6px;">${renderInlineHtml(item)}</td>
    </tr>`).join("");
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 12px;">${items}</table>`;
}

function renderTable(table: EmailTable): string {
  const header = table.headers.map((cell, index) => {
    const tone = index === 0
      ? "color:#1F2937;background:#FAFAFA;"
      : index % 2 === 1
        ? "color:#7C3AED;background:#F5F3FF;"
        : "color:#B45309;background:#FFFBEB;";
    return `<th scope="col" style="${tone}padding:10px 12px;border-bottom:2px solid #E5E7EB;border-left:${index === 0 ? 0 : 1}px solid #E5E7EB;font-family:${FONT_STACK};font-size:10px;font-weight:700;line-height:1.35;text-align:left;vertical-align:top;word-break:break-word;">${renderInlineHtml(cell)}</th>`;
  }).join("");
  const rows = table.rows.map((row) => {
    const cells = row.map((cell, index) => {
      const feature = index === 0;
      return `<td style="${feature ? "color:#1F2937;background:#FAFAFA;font-weight:600;" : "color:#374151;background:#FFFFFF;"}padding:11px 12px;border-bottom:1px solid #F3F4F6;border-left:${feature ? 0 : 1}px solid #F3F4F6;font-family:${FONT_STACK};font-size:10px;line-height:1.55;vertical-align:top;word-break:break-word;">${renderInlineHtml(cell)}</td>`;
    }).join("");
    return `<tr>${cells}</tr>`;
  }).join("");
  return `<table role="table" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:16px 0;border:1px solid #E5E7EB;border-radius:10px;border-collapse:separate;border-spacing:0;overflow:hidden;table-layout:fixed;"><thead><tr>${header}</tr></thead><tbody>${rows}</tbody></table>`;
}

function renderBlocks(blocks: EmailBlock[]): string {
  let firstHeading = true;
  return blocks.map((block) => {
    if (block.kind === "heading") {
      const html = `<h3 style="font-family:${FONT_STACK};font-size:14px;font-weight:700;color:#1F2937;margin:${firstHeading ? 0 : 20}px 0 10px;padding-bottom:6px;border-bottom:2px solid #7C3AED;display:inline-block;line-height:1.4;">${escapeHtml(block.text)}</h3>`;
      firstHeading = false;
      return html;
    }
    if (block.kind === "paragraph") return `<p style="font-family:${FONT_STACK};font-size:13px;color:#374151;line-height:1.75;margin:0 0 12px;">${renderInlineHtml(block.text)}</p>`;
    if (block.kind === "list") return renderList(block);
    if (block.kind === "callout") return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:16px 0;"><tr><td style="background:#F5F3FF;border-left:3px solid #7C3AED;padding:14px 18px;border-radius:0 8px 8px 0;"><p style="font-family:${FONT_STACK};font-size:12.5px;color:#4B5563;line-height:1.65;margin:0;">${renderInlineHtml(block.text)}</p></td></tr></table>`;
    return renderTable(block.table);
  }).join("");
}

function comparisonBlocks(comparison: ComparisonData): { html: string; text: string } {
  const normalized = ComparisonDataSchema.parse(normalizeComparison(comparison));
  const tables: string[] = [];
  const textTables: string[] = [];
  for (let start = 0; start < normalized.columns.length; start += 2) {
    const indexes = normalized.columns.slice(start, start + 2).map((_, index) => start + index);
    tables.push(renderTable({
      headers: ["Feature", ...indexes.map((index) => normalized.columns[index])],
      rows: normalized.rows.map((row) => [row.feature, ...indexes.map((index) => row.values[index])]),
    }));
    textTables.push([
      ["Feature", ...indexes.map((index) => normalized.columns[index])].join("\t"),
      ...normalized.rows.map((row) => [row.feature, ...indexes.map((index) => row.values[index])].join("\t")),
    ].join("\n"));
  }
  const html = `<h3 style="font-family:${FONT_STACK};font-size:14px;font-weight:700;color:#1F2937;margin:0 0 10px;padding-bottom:6px;border-bottom:2px solid #7C3AED;display:inline-block;line-height:1.4;">${escapeHtml(normalized.title)}</h3><p style="font-family:${FONT_STACK};font-size:13px;color:#374151;line-height:1.75;margin:0 0 12px;">${renderInlineHtml(normalized.subtitle)}</p>${tables.join("")}<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:16px 0;"><tr><td style="background:#F5F3FF;border-left:3px solid #7C3AED;padding:14px 18px;border-radius:0 8px 8px 0;"><p style="font-family:${FONT_STACK};font-size:12.5px;color:#4B5563;line-height:1.65;margin:0;"><strong style="color:#7C3AED;">Bottom line:</strong> ${renderInlineHtml(normalized.takeaway)}</p></td></tr></table>`;
  const text = [normalized.title, normalized.subtitle, ...textTables, `Bottom line: ${cleanPlainText(normalized.takeaway)}`].join("\n\n");
  return { html, text };
}

function readBrandAsset(fileName: string): Buffer {
  return fs.readFileSync(path.join(process.cwd(), "public", "brand", fileName));
}

function isLocalHost(hostname: string): boolean {
  const host = hostname.toLowerCase();
  return host === "localhost" || host === "127.0.0.1" || host === "0.0.0.0" || host === "[::1]" || host === "::1";
}

function resolveAppUrl(value: string): { href: string; host: string; isPublic: boolean } {
  const candidates = [
    process.env.APP_BASE_URL,
    process.env.NEXT_PUBLIC_SITE_URL,
    value,
    process.env.DEPLOY_PRIME_URL,
    process.env.DEPLOY_URL,
    process.env.URL,
  ];
  let localFallback: { href: string; host: string; isPublic: boolean } | null = null;
  for (const candidate of candidates) {
    if (!candidate) continue;
    try {
      const url = new URL(candidate);
      if (url.protocol !== "http:" && url.protocol !== "https:") continue;
      url.pathname = "/generate";
      url.search = "";
      url.hash = "";
      if (isLocalHost(url.hostname)) {
        localFallback ??= { href: url.toString(), host: url.host, isPublic: false };
        continue;
      }
      return { href: url.toString(), host: url.host, isPublic: true };
    } catch {
      // Try the next configured origin. Invalid values are never rendered.
    }
  }
  return localFallback ?? { href: "#", host: "EquityIQ", isPublic: false };
}

function resolveGreeting(input: ArtifactEmailInput): string {
  const recipient = input.recipient?.trim().toLowerCase();
  const authenticatedEmail = input.authenticatedUser?.email?.trim().toLowerCase();
  if (!recipient || !authenticatedEmail || recipient !== authenticatedEmail) return "there";
  const firstName = input.authenticatedUser?.name?.trim().split(/\s+/)[0];
  return firstName || "there";
}

function blocksToText(blocks: EmailBlock[]): string {
  return blocks.map((block) => {
    if (block.kind === "heading") return block.text;
    if (block.kind === "paragraph" || block.kind === "callout") return cleanPlainText(block.text);
    if (block.kind === "list") return block.items.map((item, index) => `${block.ordered ? `${index + 1}.` : "-"} ${cleanPlainText(item)}`).join("\n");
    return [block.table.headers.join("\t"), ...block.table.rows.map((row) => row.join("\t"))].join("\n");
  }).join("\n\n");
}

export function buildArtifactEmail(input: ArtifactEmailInput): ArtifactEmail {
  const question = normalizeGeneratedText(input.question || input.title);
  const title = normalizeArtifactTitle(input.title, question);
  const app = resolveAppUrl(input.appUrl);
  const greeting = resolveGreeting(input);
  const comparison = input.comparison
    ? ComparisonDataSchema.parse(normalizeComparison(input.comparison))
    : undefined;
  const blocks = comparison ? [] : parseEmailBlocks(input.bodyMarkdown);
  const comparisonContent = comparison ? comparisonBlocks(comparison) : null;
  const bodyHtml = comparisonContent?.html || renderBlocks(blocks);
  const bodyText = comparisonContent?.text || blocksToText(blocks);
  const badge = comparison ? "Comparison" : "Answer";
  const subject = buildEmailSubject({ question: input.question, title, comparison });
  const showTitle = !isRedundantArtifactTitle(title, question);
  const answerLabelMargin = showTitle ? 8 : 14;
  const answerHeaderHtml = comparison
    ? `<p style="font-family:${FONT_STACK};font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#7C3AED;margin:0 0 8px;">Your Answer</p>`
    : `<p style="font-family:${FONT_STACK};font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#7C3AED;margin:0 0 ${answerLabelMargin}px;">Your Answer</p>${showTitle ? `<h1 style="font-family:${FONT_STACK};font-size:22px;font-weight:700;color:#111827;line-height:1.3;margin:0 0 18px;word-break:break-word;">${escapeHtml(title)}</h1>` : ""}`;
  const answerHeaderText = comparison || !showTitle ? "Your Answer" : `Your Answer\n${title}`;
  const appLink = `<a href="${escapeHtml(app.href)}" target="_blank" style="font-family:${FONT_STACK};font-size:12px;font-weight:600;color:#7C3AED;text-decoration:none;">View in EquityIQ &rarr;</a>`;
  const footerUrl = app.isPublic
    ? `<p style="font-family:${FONT_STACK};font-size:9px;color:rgba(255,255,255,0.3);margin:8px 0 0;text-align:center;">${escapeHtml(app.host)}</p>`
    : "";
  const outerDeliveryNote = app.isPublic
    ? `You received this email because you shared content from <a href="${escapeHtml(app.href)}" target="_blank" style="color:#7C3AED;text-decoration:none;">EquityIQ</a>. This is a one-time delivery, not a subscription.`
    : "You received this email because you shared content from EquityIQ. This is a one-time delivery, not a subscription.";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(subject)}</title>
<style type="text/css">
  @media only screen and (max-width:480px) {
    .eq-shell-pad { padding:16px 8px !important; }
    .eq-header-pad, .eq-content-pad, .eq-info-pad, .eq-footer-pad { padding-left:20px !important; padding-right:20px !important; }
    .eq-logo { height:${BRAND_LOCKUP.email.mobileHeight}px !important; width:auto !important; }
    .eq-header-separator { margin-left:7px !important; margin-right:7px !important; }
    .eq-brand-mark { font-size:11px !important; }
    .eq-footer-row > td { display:block !important; width:100% !important; text-align:left !important; }
    .eq-footer-logos { margin-top:12px !important; text-align:left !important; }
    .eq-cta { display:block !important; padding-left:20px !important; padding-right:20px !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background-color:#EFF1F4;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${escapeHtml(subject)}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#EFF1F4" style="background-color:#EFF1F4;">
  <tr>
    <td class="eq-shell-pad" align="center" style="padding:36px 16px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF" style="max-width:600px;width:100%;background-color:#FFFFFF;border:1px solid #D9DEE7;border-radius:8px;border-collapse:separate;overflow:hidden;box-shadow:0 8px 24px rgba(15,23,42,0.12);">
        <tr>
          <td class="eq-header-pad" style="background-color:#1C1B2E;background:linear-gradient(160deg,#1C1B2E 0%,#2D2A4A 50%,#1C1B2E 100%);padding:16px 28px;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td style="vertical-align:middle;white-space:nowrap;">
                  <img class="eq-logo eq-header-logo" src="cid:equityiq-qapita-logo" alt="Qapita" width="${BRAND_LOCKUP.email.qapitaWidth}" height="${BRAND_LOCKUP.email.height}" style="height:${BRAND_LOCKUP.email.height}px;width:${BRAND_LOCKUP.email.qapitaWidth}px;vertical-align:middle;">
                  <span class="eq-header-separator" style="display:inline-block;width:1px;height:${BRAND_LOCKUP.email.dividerHeight}px;background:rgba(255,255,255,0.15);vertical-align:middle;margin:0 ${BRAND_LOCKUP.email.gap}px;"></span>
                  <img class="eq-logo eq-header-logo" src="cid:equityiq-naspp-logo" alt="NASPP" width="${BRAND_LOCKUP.email.nasppWidth}" height="${BRAND_LOCKUP.email.height}" style="height:${BRAND_LOCKUP.email.height}px;width:${BRAND_LOCKUP.email.nasppWidth}px;vertical-align:middle;">
                </td>
                <td style="text-align:right;vertical-align:middle;white-space:nowrap;">
                  <span class="eq-brand-mark" style="font-family:${FONT_STACK};font-size:13px;font-weight:700;color:#F5C518;letter-spacing:0.5px;">EquityIQ</span>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="eq-content-pad" style="background-color:#FFFFFF;padding:28px 32px 0;">
            <p style="font-family:${FONT_STACK};font-size:14px;color:#1F2937;line-height:1.6;margin:0 0 6px;font-weight:600;">Hi ${escapeHtml(greeting)},</p>
            <p style="font-family:${FONT_STACK};font-size:13px;color:#6B7280;line-height:1.6;margin:0;">You shared this from EquityIQ. The full answer is included below.</p>
          </td>
        </tr>
        <tr>
          <td class="eq-info-pad" style="background:#F9FAFB;padding:16px 32px;border-bottom:1px solid #E5E7EB;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td style="vertical-align:middle;">
                  <span style="font-family:${FONT_STACK};font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#7C3AED;background:rgba(124,58,237,0.08);padding:4px 12px;border-radius:4px;">${badge}</span>
                </td>
                <td style="text-align:right;vertical-align:middle;">
                  ${appLink}
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="eq-content-pad" style="background-color:#FFFFFF;padding:28px 32px 0;">
            <p style="font-family:${FONT_STACK};font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#9CA3AF;margin:0 0 8px;">Your Question</p>
            <p style="font-family:${FONT_STACK};font-size:17px;font-weight:600;color:#1F2937;line-height:1.5;margin:0;word-break:break-word;">${escapeHtml(question)}</p>
          </td>
        </tr>
        <tr>
          <td class="eq-content-pad" style="background-color:#FFFFFF;padding:24px 32px;">${answerHeaderHtml}${bodyHtml}</td>
        </tr>
        <tr>
          <td class="eq-content-pad" style="background-color:#FFFFFF;padding:0 32px;"><div style="border-top:1px solid #E5E7EB;"></div></td>
        </tr>
        <tr>
          <td class="eq-content-pad" style="background-color:#FFFFFF;padding:24px 32px;text-align:center;">
            <a class="eq-cta" href="${escapeHtml(app.href)}" target="_blank" style="display:inline-block;background:#7C3AED;color:#ffffff;font-family:${FONT_STACK};font-size:14px;font-weight:600;text-decoration:none;padding:12px 32px;border-radius:8px;min-height:20px;">Open in EquityIQ</a>
            <p style="font-family:${FONT_STACK};font-size:11px;color:#9CA3AF;margin:10px 0 0;">Ask another question or explore more equity topics.</p>
          </td>
        </tr>
        <tr>
          <td class="eq-footer-pad" style="background-color:#1C1B2E;background:linear-gradient(160deg,#1C1B2E 0%,#2D2A4A 50%,#1C1B2E 100%);padding:16px 28px;">
            <p style="font-family:${FONT_STACK};font-size:9px;color:rgba(255,255,255,0.5);line-height:1.5;margin:0 0 10px;">${DISCLAIMER}</p>
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
              <tr class="eq-footer-row">
                <td style="vertical-align:middle;white-space:nowrap;">
                  <span style="display:inline-block;width:5px;height:5px;border-radius:50%;background:#22C55E;vertical-align:middle;"></span>
                  <span style="font-family:${FONT_STACK};font-size:9px;color:rgba(255,255,255,0.5);font-weight:500;vertical-align:middle;margin-left:5px;">Endorsed by NASPP</span>
                </td>
                <td class="eq-footer-logos" style="text-align:right;vertical-align:middle;white-space:nowrap;">
                  <img class="eq-logo eq-footer-logo" src="cid:equityiq-qapita-logo" alt="Qapita" width="${BRAND_LOCKUP.email.qapitaWidth}" height="${BRAND_LOCKUP.email.height}" style="height:${BRAND_LOCKUP.email.height}px;width:${BRAND_LOCKUP.email.qapitaWidth}px;opacity:1;vertical-align:middle;">
                  <span style="display:inline-block;width:1px;height:${BRAND_LOCKUP.email.dividerHeight}px;background:rgba(255,255,255,0.15);vertical-align:middle;margin:0 ${BRAND_LOCKUP.email.gap}px;"></span>
                  <img class="eq-logo eq-footer-logo" src="cid:equityiq-naspp-logo" alt="NASPP" width="${BRAND_LOCKUP.email.nasppWidth}" height="${BRAND_LOCKUP.email.height}" style="height:${BRAND_LOCKUP.email.height}px;width:${BRAND_LOCKUP.email.nasppWidth}px;opacity:1;vertical-align:middle;">
                </td>
              </tr>
            </table>
            ${footerUrl}
          </td>
        </tr>
      </table>
      <p style="font-family:${FONT_STACK};font-size:10px;color:#9CA3AF;text-align:center;margin:16px 0 0;">${outerDeliveryNote}</p>
    </td>
  </tr>
</table>
</body>
</html>`;

  const text = [
    `Hi ${greeting},`,
    "You shared this from EquityIQ. The full answer is included below.",
    "",
    badge,
    "Your Question",
    question,
    "",
    answerHeaderText,
    bodyText,
    "",
    ...(app.isPublic ? [`Open in EquityIQ: ${app.href}`] : []),
    "",
    DISCLAIMER,
    "Endorsed by NASPP",
    "You received this email because you shared content from EquityIQ. This is a one-time delivery, not a subscription.",
  ].join("\n");

  return {
    subject,
    html,
    text,
    inlineAttachments: [
      {
        filename: BRAND_ASSETS.qapita,
        content: readBrandAsset(BRAND_ASSETS.qapita),
        contentType: "image/png",
        contentId: "equityiq-qapita-logo",
      },
      {
        filename: BRAND_ASSETS.naspp,
        content: readBrandAsset(BRAND_ASSETS.naspp),
        contentType: "image/png",
        contentId: "equityiq-naspp-logo",
      },
    ],
  };
}
