/* eslint-disable jsx-a11y/alt-text */
import React from "react";
import path from "node:path";
import {
  Canvas,
  Document,
  Font,
  Image,
  Page,
  Text,
  View,
} from "@react-pdf/renderer";
import type { Style } from "@react-pdf/types";
import type { ComparisonData } from "../llm/types";
import type { PdfBlock, PdfTable } from "./markdown";
import { BRAND_LOCKUP } from "../brand/lockup";
import { isRedundantArtifactTitle } from "../llm/title";

const interRegularFont = path.join(process.cwd(), "public", "fonts", "EquityIQ-Regular.ttf");
const interBoldFont = path.join(process.cwd(), "public", "fonts", "EquityIQ-Bold.ttf");
Font.register({
  family: "Inter",
  // React-PDF's fontkit subsetter cannot reliably embed the variable WOFF2
  // emitted by next/font. These local static faces keep PDF generation
  // deterministic and preserve the supplied typography hierarchy.
  fonts: [
    { src: interRegularFont, fontWeight: 400 },
    { src: interBoldFont, fontWeight: 500 },
    { src: interBoldFont, fontWeight: 600 },
    { src: interBoldFont, fontWeight: 700 },
  ],
});

const DISCLAIMER =
  "This content is generated by EquityIQ for informational purposes only. It does not constitute legal, tax, or financial advice. Consult qualified professionals before making decisions based on this information.";

const styles = {
  page: {
    position: "relative" as const,
    paddingTop: 82,
    paddingBottom: 102,
    paddingHorizontal: 48,
    fontFamily: "Inter",
    backgroundColor: "#ffffff",
  },
  gradient: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
  },
  header: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    height: 64,
    paddingHorizontal: 48,
    paddingVertical: 17,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    backgroundColor: "#1C1B2E",
  },
  headerLeft: { flexDirection: "row" as const, alignItems: "center" as const },
  headerLogo: { height: BRAND_LOCKUP.pdf.height, objectFit: "contain" as const },
  qapitaHeaderLogo: { width: BRAND_LOCKUP.pdf.qapitaWidth },
  nasppHeaderLogo: { width: BRAND_LOCKUP.pdf.nasppWidth, marginLeft: BRAND_LOCKUP.pdf.gap },
  headerDivider: { width: 1, height: BRAND_LOCKUP.pdf.dividerHeight, marginLeft: BRAND_LOCKUP.pdf.gap, backgroundColor: "rgba(255,255,255,0.15)" },
  headerRight: { flexDirection: "row" as const, alignItems: "center" as const },
  equityIqMark: { color: "#F5C518", fontSize: 13, fontWeight: 700, letterSpacing: 0.5 },
  date: { marginLeft: 10, color: "rgba(255,255,255,0.45)", fontSize: 10 },
  question: { paddingTop: 2 },
  questionLabel: { marginBottom: 8, color: "#9CA3AF", fontSize: 10, fontWeight: 600, letterSpacing: 1.2 },
  questionText: { color: "#1F2937", fontSize: 16, fontWeight: 600, lineHeight: 1.5 },
  title: { marginTop: 28, marginBottom: 20, color: "#111827", fontSize: 22, fontWeight: 700, lineHeight: 1.3 },
  heading: { alignSelf: "flex-start" as const, marginTop: 24, marginBottom: 10, paddingBottom: 6, borderBottomWidth: 2, borderBottomColor: "#7C3AED" },
  headingText: { color: "#1F2937", fontSize: 14, fontWeight: 700, lineHeight: 1.4 },
  firstHeading: { marginTop: 0 },
  paragraph: { marginBottom: 12, color: "#374151", fontSize: 13, lineHeight: 1.75 },
  bold: { color: "#111827", fontWeight: 600 },
  list: { marginBottom: 12 },
  listItem: { flexDirection: "row" as const, marginBottom: 6, paddingLeft: 8 },
  bullet: { width: 16, color: "#7C3AED", fontSize: 13, fontWeight: 700 },
  listText: { flex: 1, color: "#374151", fontSize: 13, lineHeight: 1.65 },
  callout: { marginVertical: 16, padding: 14, paddingLeft: 18, borderLeftWidth: 3, borderLeftColor: "#7C3AED", borderTopRightRadius: 8, borderBottomRightRadius: 8, backgroundColor: "#F5F3FF" },
  calloutText: { color: "#4B5563", fontSize: 12.5, lineHeight: 1.65 },
  table: { marginVertical: 16, borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 10, overflow: "hidden" as const },
  tableRow: { flexDirection: "row" as const },
  tableHeader: { paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: 2, borderBottomColor: "#E5E7EB", color: "#6B7280", backgroundColor: "#F9FAFB", fontSize: 9.5, fontWeight: 700, letterSpacing: 0.4, lineHeight: 1.35 },
  tableHeaderTopicA: { color: "#7C3AED", backgroundColor: "#F5F3FF", borderLeftWidth: 1, borderLeftColor: "#E5E7EB" },
  tableHeaderTopicB: { color: "#B45309", backgroundColor: "#FFFBEB", borderLeftWidth: 1, borderLeftColor: "#E5E7EB" },
  tableFeature: { width: "25%" as const, paddingVertical: 11, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: "#F3F4F6", color: "#1F2937", backgroundColor: "#FAFAFA", fontSize: 9.5, fontWeight: 600, lineHeight: 1.55 },
  tableCell: { flex: 1, paddingVertical: 11, paddingHorizontal: 12, borderLeftWidth: 1, borderBottomWidth: 1, borderLeftColor: "#F3F4F6", borderBottomColor: "#F3F4F6", color: "#374151", fontSize: 9.5, lineHeight: 1.55 },
  tableCellTopicA: { color: "#4B5563" },
  tableCellTopicB: { color: "#4B5563" },
  footer: {
    position: "absolute" as const,
    bottom: 0,
    left: 0,
    right: 0,
    minHeight: 92,
    paddingHorizontal: 48,
    paddingVertical: 13,
    backgroundColor: "#1C1B2E",
  },
  disclaimer: { maxWidth: "85%" as const, color: "rgba(255,255,255,0.5)", fontSize: 9.5, lineHeight: 1.55 },
  footerBottom: { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "space-between" as const, marginTop: 6 },
  endorsement: { flexDirection: "row" as const, alignItems: "center" as const },
  endorsementDot: { width: 5, height: 5, marginRight: 7, borderRadius: 3, backgroundColor: "#22C55E" },
  endorsementText: { color: "rgba(255,255,255,0.5)", fontSize: 9.5, fontWeight: 500 },
  footerLogos: { flexDirection: "row" as const, alignItems: "center" as const },
  footerLogo: { height: BRAND_LOCKUP.pdf.height, objectFit: "contain" as const, opacity: 1 },
  qapitaFooterLogo: { width: BRAND_LOCKUP.pdf.qapitaWidth },
  nasppFooterLogo: { width: BRAND_LOCKUP.pdf.nasppWidth, marginLeft: BRAND_LOCKUP.pdf.gap },
  footerDivider: { width: 1, height: BRAND_LOCKUP.pdf.dividerHeight, marginLeft: BRAND_LOCKUP.pdf.gap, backgroundColor: "rgba(255,255,255,0.15)" },
};

function inlineText(text: string, keyPrefix: string): React.ReactNode[] {
  const pattern = /(\*\*[^*]+\*\*|__[^_]+__|`[^`]+`|\[[^\]]+\]\([^)]+\))/g;
  const parts = text.split(pattern);
  return parts.filter((part) => part.length > 0).map((part, index) => {
    const key = `${keyPrefix}-${index}`;
    if ((part.startsWith("**") && part.endsWith("**")) || (part.startsWith("__") && part.endsWith("__"))) {
      return <Text key={key} style={styles.bold}>{part.slice(2, -2)}</Text>;
    }
    if (part.startsWith("`") && part.endsWith("`")) return <Text key={key}>{part.slice(1, -1)}</Text>;
    const link = part.match(/^\[([^\]]+)\]\([^)]+\)$/);
    return <Text key={key}>{link?.[1] ?? part}</Text>;
  });
}

function InlineText({ text, style, keyPrefix }: { text: string; style: Style | Style[]; keyPrefix: string }) {
  return <Text style={style}>{inlineText(text, keyPrefix)}</Text>;
}

function renderList(block: Extract<PdfBlock, { kind: "list" }>, key: string) {
  return (
    <View key={key} style={styles.list}>
      {block.items.map((item, index) => (
        <View key={`${key}-${index}`} style={styles.listItem}>
          <Text style={styles.bullet}>{block.ordered ? `${index + 1}.` : "•"}</Text>
          <InlineText text={item} style={styles.listText} keyPrefix={`${key}-${index}`} />
        </View>
      ))}
    </View>
  );
}

function renderTable(table: PdfTable, key: string) {
  return (
    <View key={key} style={styles.table} wrap={false}>
      <View style={styles.tableRow}>
        {table.headers.map((header, index) => (
          <Text key={`${key}-head-${index}`} style={index === 0 ? [styles.tableHeader, styles.tableFeature] : [styles.tableHeader, styles.tableCell, index % 2 === 1 ? styles.tableHeaderTopicA : styles.tableHeaderTopicB]}>
            {header}
          </Text>
        ))}
      </View>
      {table.rows.map((row, rowIndex) => (
        <View key={`${key}-row-${rowIndex}`} style={styles.tableRow} wrap={false}>
          {row.map((cell, cellIndex) => (
            <InlineText key={`${key}-${rowIndex}-${cellIndex}`} text={cell} style={cellIndex === 0 ? styles.tableFeature : [styles.tableCell, cellIndex % 2 === 1 ? styles.tableCellTopicA : styles.tableCellTopicB]} keyPrefix={`${key}-${rowIndex}-${cellIndex}`} />
          ))}
        </View>
      ))}
    </View>
  );
}

function renderBlock(block: PdfBlock, key: string, firstHeading = false): React.ReactNode {
  if (block.kind === "heading") return <View key={key} style={firstHeading ? [styles.heading, styles.firstHeading] : styles.heading} minPresenceAhead={32} wrap={false}><Text style={styles.headingText}>{block.text}</Text></View>;
  if (block.kind === "paragraph") return <InlineText keyPrefix={key} key={key} text={block.text} style={styles.paragraph} />;
  if (block.kind === "list") return renderList(block, key);
  if (block.kind === "callout") return <View key={key} style={styles.callout} wrap={false}><InlineText text={block.text} style={styles.calloutText} keyPrefix={key} /></View>;
  return renderTable(block.table, key);
}

function renderBlocks(blocks: PdfBlock[]) {
  return blocks.map((block, index) => renderBlock(block, `block-${index}`, block.kind === "heading" && index === 0));
}

function comparisonTable(data: ComparisonData, topicIndexes: number[], rows: ComparisonData["rows"], key: string) {
  const columns = ["Feature", ...topicIndexes.map((index) => data.columns[index])];
  return (
    <View key={key} style={styles.table} wrap={false}>
      <View style={styles.tableRow}>
        {columns.map((column, index) => (
          <Text key={`${key}-header-${index}`} style={index === 0 ? [styles.tableFeature, styles.tableHeader] : [styles.tableCell, styles.tableHeader, index % 2 === 1 ? styles.tableHeaderTopicA : styles.tableHeaderTopicB]}>{column}</Text>
        ))}
      </View>
      {rows.map((row, rowIndex) => (
        <View key={`${key}-row-${rowIndex}`} style={styles.tableRow} wrap={false}>
          <Text style={styles.tableFeature}>{row.feature}</Text>
          {topicIndexes.map((topicIndex, valueIndex) => (
            <InlineText key={`${key}-cell-${rowIndex}-${valueIndex}`} text={row.values[topicIndex]} style={[styles.tableCell, valueIndex % 2 === 0 ? styles.tableCellTopicA : styles.tableCellTopicB]} keyPrefix={`${key}-${rowIndex}-${valueIndex}`} />
          ))}
        </View>
      ))}
    </View>
  );
}

function renderComparison(data: ComparisonData) {
  const topicGroups: number[][] = [];
  for (let index = 0; index < data.columns.length; index += 2) topicGroups.push([index, ...([index + 1].filter((item) => item < data.columns.length))]);
  const sequences: React.ReactNode[] = [];
  let sequenceIndex = 0;
  for (const topicIndexes of topicGroups) {
    const pageSize = sequenceIndex === 0 ? 2 : 3;
    for (let rowIndex = 0; rowIndex < data.rows.length; rowIndex += pageSize) {
      const rows = data.rows.slice(rowIndex, rowIndex + pageSize);
      sequences.push(
        <View key={`comparison-${sequenceIndex}`} break={sequenceIndex > 0}>
          {comparisonTable(data, topicIndexes, rows, `comparison-table-${sequenceIndex}`)}
        </View>
      );
      sequenceIndex += 1;
    }
  }
  sequences.push(
    <View key="comparison-takeaway" style={styles.callout} wrap={false}>
      <Text style={{ color: "#7C3AED", fontSize: 12, fontWeight: 700, letterSpacing: 0.5, marginBottom: 6 }}>Bottom Line</Text>
      <InlineText text={data.takeaway} style={styles.calloutText} keyPrefix="comparison-takeaway-text" />
    </View>
  );
  return sequences;
}

type PdfPainter = {
  fillColor: (color: string) => PdfPainter;
  rect: (x: number, y: number, width: number, height: number) => PdfPainter;
  fill: () => PdfPainter;
};

function paintBrandGradient(painter: PdfPainter, width: number, height: number): null {
  const start = [0x1c, 0x1b, 0x2e];
  const middle = [0x2d, 0x2a, 0x4a];
  const bands = 64;
  const segmentWidth = width / bands;
  for (let index = 0; index < bands; index += 1) {
    const position = index / (bands - 1);
    const progress = position <= 0.5 ? position * 2 : (position - 0.5) * 2;
    const from = position <= 0.5 ? start : middle;
    const to = position <= 0.5 ? middle : start;
    const color = `#${from.map((channel, channelIndex) => Math.round(channel + (to[channelIndex] - channel) * progress).toString(16).padStart(2, "0")).join("")}`;
    painter.fillColor(color).rect(index * segmentWidth, 0, segmentWidth + 0.5, height).fill();
  }
  return null;
}

function HeaderContent({ date, nasppLogoSrc, qapitaLogoSrc }: Pick<Props, "date" | "nasppLogoSrc" | "qapitaLogoSrc">) {
  return (
    <>
      <Canvas style={styles.gradient} paint={paintBrandGradient} />
      <View style={styles.headerLeft}>
        <Image src={qapitaLogoSrc} style={[styles.headerLogo, styles.qapitaHeaderLogo]} />
        <View style={styles.headerDivider} />
        <Image src={nasppLogoSrc} style={[styles.headerLogo, styles.nasppHeaderLogo]} />
      </View>
      <View style={styles.headerRight}><Text style={styles.equityIqMark}>EquityIQ</Text><Text style={styles.date}>{date}</Text></View>
    </>
  );
}

function FooterContent({ nasppLogoSrc, qapitaLogoSrc }: Pick<Props, "nasppLogoSrc" | "qapitaLogoSrc">) {
  return (
    <>
      <Canvas style={styles.gradient} paint={paintBrandGradient} />
      <Text style={styles.disclaimer}>{DISCLAIMER}</Text>
      <View style={styles.footerBottom}>
        <View style={styles.endorsement}><View style={styles.endorsementDot} /><Text style={styles.endorsementText}>Endorsed by NASPP</Text></View>
        <View style={styles.footerLogos}><Image src={qapitaLogoSrc} style={[styles.footerLogo, styles.qapitaFooterLogo]} /><View style={styles.footerDivider} /><Image src={nasppLogoSrc} style={[styles.footerLogo, styles.nasppFooterLogo]} /></View>
      </View>
    </>
  );
}

type Props = {
  title: string;
  question: string;
  bodyMarkdown: string;
  blocks: PdfBlock[];
  comparison?: ComparisonData;
  date: string;
  nasppLogoSrc: string;
  qapitaLogoSrc: string;
};

export function EquityBriefPDF({ title, question, blocks, comparison, date, nasppLogoSrc, qapitaLogoSrc }: Props) {
  const showTitle = !isRedundantArtifactTitle(title, question);
  return (
    <Document>
      <Page size="LETTER" style={styles.page} wrap>
        <View style={styles.question}>
          <Text style={styles.questionLabel}>Your Question</Text>
          <Text style={styles.questionText}>{question}</Text>
        </View>

        {showTitle ? <Text style={styles.title}>{title}</Text> : null}
        {comparison ? renderComparison(comparison) : renderBlocks(blocks)}

        <View fixed wrap={false} style={styles.header} render={() => <HeaderContent date={date} nasppLogoSrc={nasppLogoSrc} qapitaLogoSrc={qapitaLogoSrc} />} />

        <View fixed wrap={false} style={styles.footer} render={() => <FooterContent nasppLogoSrc={nasppLogoSrc} qapitaLogoSrc={qapitaLogoSrc} />} />
      </Page>
    </Document>
  );
}
