import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { buildArtifactEmail } from "../lib/email/artifact-email";

const baseInput = {
  title: "Tender offer <review> & planning",
  question: "How does a tender offer work for private company employees, and what should they consider before deciding whether to participate?",
  bodyMarkdown: [
    "Subject: Old generated subject",
    "",
    "Hi Pranav,",
    "",
    "## Tax treatment:.",
    "The **spread** and timing matter. A source marker 【nodeId=1.1】 must not appear.",
    "",
    "- Review the offer terms",
    "- Confirm the company process",
    "",
    "> **Key distinction:** NASPP and MyStockOptions are not generated prose references.",
    "",
    "Best regards,",
    "EquityIQ",
  ].join("\n"),
  appUrl: "https://preview.example/generate",
  recipient: "pranav@example.com",
  authenticatedUser: { name: "Pranav Kumar", email: "PRANAV@example.com" },
};

describe("branded artifact email", () => {
  beforeEach(() => {
    for (const name of ["APP_BASE_URL", "NEXT_PUBLIC_SITE_URL", "DEPLOY_PRIME_URL", "DEPLOY_URL", "URL"]) {
      vi.stubEnv(name, "");
    }
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("renders the supplied structure with normalized, escaped generated content", () => {
    const result = buildArtifactEmail(baseInput);

    expect(result.html).toContain("Hi Pranav,");
    expect(result.html).toContain("Your Question");
    expect(result.html).toContain("Tender offer &lt;review&gt; &amp; planning");
    expect(result.html).toContain("How does a tender offer work for private company employees");
    expect(result.html).toContain("Tax treatment");
    expect(result.html).toContain("<strong style=");
    expect(result.html).toContain("background:#F5F3FF;border-left:3px solid #7C3AED");
    expect(result.html).toContain("Open in EquityIQ");
    expect(result.html).toContain('href="https://preview.example/generate"');
    expect(result.html).toContain("Endorsed by NASPP");
    expect(result.html).toContain("This content is generated by EquityIQ for informational purposes only.");
    expect(result.html).toContain("cid:equityiq-qapita-logo");
    expect(result.html).toContain("cid:equityiq-naspp-logo");
    expect(result.inlineAttachments).toHaveLength(2);
    expect(result.inlineAttachments.every((attachment) => attachment.content.length > 0)).toBe(true);
    expect(result.html).not.toContain("Subject: Old generated subject");
    expect(result.html).not.toContain("Implementation Notes");
    expect(result.html).not.toContain("Reference Guide");
    expect(result.html).not.toContain("nodeId");
    expect(result.html).not.toContain("MyStockOptions");
    expect(result.html).not.toContain("NASPP and");
    expect(result.html).not.toContain("—");
    expect(result.html).not.toContain("{{");
    expect(result.text).toContain(baseInput.question);
    expect(result.text).not.toContain("**");
    expect(result.text).not.toContain("nodeId");
    expect(result.text).not.toContain("MyStockOptions");
  });

  it("uses a generic greeting for another recipient and falls back to the title", () => {
    const result = buildArtifactEmail({
      ...baseInput,
      question: undefined,
      recipient: "colleague@example.com",
      bodyMarkdown: "A direct answer.",
    });

    expect(result.html).toContain("Hi there,");
    expect(result.html).not.toContain("Hi Pranav,");
    expect(result.html).toContain("Your Question");
    expect(result.html).toContain("Tender offer &lt;review&gt; &amp; planning");
  });

  it("uses the complete question for a professional subject, a visible card, and matched compact lockups", () => {
    const result = buildArtifactEmail({
      ...baseInput,
      title: "an ISO",
      question: "What is an ISO?",
      bodyMarkdown: "A concise definition.",
      appUrl: "http://localhost:3000/generate",
    });

    expect(result.subject).toBe("EquityIQ answer: What is an ISO?");
    expect(result.html).toContain("Incentive stock options (ISOs)");
    expect(result.html.match(/href="http:\/\/localhost:3000\/generate"/g)).toHaveLength(2);
    expect(result.html).not.toContain(">localhost:3000<");
    expect(result.html).not.toContain("opacity:0.5");
    expect(result.html).not.toContain("opacity:0.4");
    expect(result.html).toContain('bgcolor="#EFF1F4"');
    expect(result.html).toContain('bgcolor="#FFFFFF"');
    expect(result.html).toContain("background-color:#FFFFFF;border:1px solid #D9DEE7");
    expect(result.html.match(/class="eq-logo eq-(?:header|footer)-logo"[^>]+height="24"/g)).toHaveLength(4);
    expect(result.html).toContain(".eq-logo { height:20px !important; width:auto !important; }");
  });

  it("shows an identical question and answer title only once in the visible email body", () => {
    const result = buildArtifactEmail({
      ...baseInput,
      title: "What is stock appreciation right",
      question: "What is stock appreciation right?",
      bodyMarkdown: "A stock appreciation right tracks appreciation above a defined base value.",
    });

    expect(result.html).toContain("What is stock appreciation right?");
    expect(result.html).not.toContain(">What is stock appreciation right</h1>");
    expect(result.text).not.toContain("What is stock appreciation right?\n\nYour Answer\nWhat is stock appreciation right");
  });

  it("renders four-topic comparisons as two email-safe tables", () => {
    const result = buildArtifactEmail({
      ...baseInput,
      comparison: {
        title: "ISO, NSO, RSU, and RSA comparison",
        subtitle: "The main distinctions in one view.",
        columns: ["ISOs", "NSOs", "RSUs", "RSAs"],
        rows: [{ feature: "Tax timing", values: ["At exercise", "At exercise", "At vesting", "At vesting"] }],
        takeaway: "Apply the award-specific conditions to the employee facts.",
      },
    });

    expect(result.html.match(/role="table"/g)).toHaveLength(2);
    expect(result.html).toContain("ISOs");
    expect(result.html).toContain("RSAs");
    expect(result.html).toContain("Bottom line:");
    expect(result.text).toContain("Feature\tISOs\tNSOs");
    expect(result.text).toContain("Feature\tRSUs\tRSAs");
    expect(result.text).toContain("Tax timing\tAt exercise\tAt exercise");
    expect(result.text).not.toContain("|");
  });

  it("does not allow unsafe generated links or HTML to escape the renderer", () => {
    const result = buildArtifactEmail({
      ...baseInput,
      appUrl: "javascript:alert(1)",
      bodyMarkdown: "[unsafe](javascript:alert(1)) [external](https://evil.example) <img src=x onerror=alert(1)>",
    });

    expect(result.html).not.toContain("javascript:");
    expect(result.html).not.toContain("evil.example");
    expect(result.html).not.toContain("<img src=x");
    expect(result.html).toContain("&lt;img src=x onerror=alert(1)&gt;");
    expect(result.html).toContain('href="#"');
  });

  it("renders ordinary Markdown tables without pipe syntax in plain text", () => {
    const result = buildArtifactEmail({
      ...baseInput,
      bodyMarkdown: [
        "| Feature | Value |",
        "| --- | --- |",
        "| Tax timing | At exercise |",
      ].join("\n"),
    });

    expect(result.html).toContain('role="table"');
    expect(result.text).toContain("Feature\tValue");
    expect(result.text).not.toContain("|");
  });
});
