export default function DisclaimerPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12">
      <h1 className="font-head text-heading text-3xl mb-6">Disclaimer</h1>
      <div className="space-y-4 text-body">
        <p>
          This is an AI-generated draft that has not been reviewed by a professional.
          It is educational only and is not tax, legal, or investment advice. US only.
        </p>
        <p>
          The content on this site is generated by AI and is provided for informational
          and educational purposes only. It does not constitute tax advice, legal advice,
          investment advice, or any other form of professional advice.
        </p>
        <p>
          Equity compensation is a complex area of law and finance that varies
          significantly based on individual circumstances. Always consult with qualified
          tax professionals, attorneys, and financial advisors before making decisions
          about your equity compensation.
        </p>
        <p>
          This site covers US equity compensation rules only. Rules differ significantly
          in other jurisdictions.
        </p>
        <p className="text-muted text-sm mt-8">
          This is a preview build. Content has not been reviewed by a licensed professional.
        </p>
      </div>
    </div>
  );
}
